### ISSUE TITLE
"Random" Segfault 

### ISSUE THREAD

**Issue by gnat42** [galkahana/PDF-Writer#145]
Hello again,
  I have a some odd behaviour occurring all of a sudden. In code that we haven't changed, but the segfault comes from PDFWriter. It only occurs on our production machine and not the matching system VM used for testing. The stacktrace is as follows:

```
#0  ObjectsContext::StartNewIndirectObject (this=0x562d88879f10) at /usr/src/debug/pdf-writer-4.0/PDFWriter/ObjectsContext.cpp:320
#1  0x00007f410ddb5e2f in PDFHummus::DocumentContext::WriteCatalogObject (this=this@entry=0x562d88879f68, inPageTreeRootObjectReference=..., inModifiedFileCopyContext=inModifiedFileCopyContext@entry=0x0)
    at /usr/src/debug/pdf-writer-4.0/PDFWriter/DocumentContext.cpp:499
#2  0x00007f410ddb81ef in PDFHummus::DocumentContext::WriteCatalogObjectOfNewPDF (this=this@entry=0x562d88879f68) at /usr/src/debug/pdf-writer-4.0/PDFWriter/DocumentContext.cpp:492
#3  0x00007f410ddc0b9c in PDFHummus::DocumentContext::FinalizeNewPDF (this=this@entry=0x562d88879f68) at /usr/src/debug/pdf-writer-4.0/PDFWriter/DocumentContext.cpp:207
#4  0x00007f410ddfe6b8 in PDFWriter::EndPDF (this=0x562d88879f10) at /usr/src/debug/pdf-writer-4.0/PDFWriter/PDFWriter.cpp:101
#5  0x00007f410e342784 in PdfWriter::writePdf(Php::Parameters&) () from /usr/lib64/php/modules/pdf.so
#6  0x00007f410e348c51 in void Php::ZendCallable::invoke<PdfWriter, &PdfWriter::writePdf>(_zend_execute_data*, _zval_struct*) () from /usr/lib64/php/modules/pdf.so
#7  0x00007f411d22dba5 in xdebug_execute_internal () from /usr/lib64/php/modules/xdebug.so
#8  0x0000562d87f5dcc4 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.2.13/Zend/zend_vm_execute.h:909
#9  0x0000562d87fc626f in execute_ex (ex=0x0) at /usr/src/debug/php-7.2.13/Zend/zend_vm_execute.h:59828
#10 0x00007f411d22ced9 in xdebug_execute_ex () from /usr/lib64/php/modules/xdebug.so
#11 0x0000562d87f5de2c in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.2.13/Zend/zend_vm_execute.h:888
#12 0x0000562d87fc626f in execute_ex (ex=0x0) at /usr/src/debug/php-7.2.13/Zend/zend_vm_execute.h:59828
#13 0x00007f411d22ced9 in xdebug_execute_ex () from /usr/lib64/php/modules/xdebug.so
```

Its code we've been using for at least a year now. It hasn't changed. I don't know why 

```
mReferencesRegistry.MarkObjectAsWritten(newObjectID,mOutputStream->GetCurrentPosition());
```
crashes on the production machine but not locally. I have the coredump but nothing looks like a normal null pointer issue etc.

Any thoughts or pointers no pun intended on what could be occurring here?

The use case is we're adding text to an existing PDF as follows:

```
void PdfWriter::writePdf(Php::Parameters &params) {
    // Iterate and print keys and values of unordered_map
    for (const auto &n : pageText ) {
//        Php::out << "PageText: [" << n.first << "] TextCount: [" << n.second.size() << "]\n";

        PDFModifiedPage thePage(&writer, n.first, true);
        AbstractContentContext* contentContext = thePage.StartContentContext();

        if (contentContext) {
			// iterate over each PdfText point
			for (const auto &iter : n.second) {
				this->writeText(iter, contentContext);
				//Php::out << "Delete iter" << std::endl;
				delete iter; //deleted because it was new PdfText() in our writeTextToPage calls
			}

			// see if there are images destined for this page and write them at the same time
			auto images = pageImages.find(n.first);

			if (images != pageImages.end()) {
				//Php::out << "Have Images: " << images->second.size() << std::endl;

				for (const auto& i : images->second) {
					//Php::out << "\tImage: [" << i->getImagePath() << "]\n";
					this->writeImage(i,contentContext);
					delete i;
				}

				pageImages.erase(images);
			}

			thePage.EndContentContext();
		}

		thePage.WritePage();
	}

//    Php::out << "Image Pages Left: " << pageImages.size() << std::endl;
    for( const auto& i : pageImages ) {
        PDFModifiedPage thePage(&writer, i.first, true);
        AbstractContentContext* contentContext = thePage.StartContentContext();
        if (contentContext) {
			// Php::out << "PageImages:[" << i.first << "] NumImages: ["<< i.second.size() <<"]\n";
			for (const auto& image : i.second) {
				this->writeImage(image, contentContext);
				delete image;
			}
			thePage.EndContentContext();
		}

		thePage.WritePage();
    }

    pageText.clear();
    pageImages.clear();
    writer.EndPDF();
```

Any help would be greatly appreciated.

**Comment by gnat42** [comment]
As a side note I've also compiled against the latest master with similar fault..

**Comment by gnat42** [comment]
mOutputStream is null, when I inspect the stacktrace and print mOutputStream its 0x0. How could that occur?

**Comment by gnat42** [comment]
yeah this is the same bug as I reported #116. Now that I'm a little more familiar with the code I'll see about coming up with a PR.
